# Generated by Django 2.1.5 on 2020-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_remove_supplier_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='vat_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
