# Generated by Django 2.1.5 on 2020-01-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_auto_20200129_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenses',
            name='confirm_spense',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
